#spring:
#  datasource:
#    url: jdbc:mysql://containers-us-west-169.railway.app:6156/railway?createDatabaseIfNotExist=true
#    username: root
#    password: V7LmV8huNX5pa9FKkGGG
#
#  sql:
#    init:
#      mode: always # you won't do this in prod, I'm just doing this for demo purposes