
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: spring-blog
    description: Menu aplication
    author: Daniel
    version: '@project.version@'
spring:
  profiles:
    active: dev
jwt:
  secret: 2c57cf3a-c804-4dc5-8cd4-93b8d8581948
  expiration: 99999999999999999